deployment = "deployment.toml"

[[contracts]]
name = "lockscript"
template_type = "Rust"

[[contracts]]
name = "centralized-crosschain"
template_type = "Rust"

[[contracts]]
name = "multisig-crosschain"
template_type = "Rust"
