schema:
	# moleculec --language rust --schema-file ./schema/blockchain.mol > ./contracts/centralized-crosschain/src/types/blockchain.rs
	moleculec --language rust --schema-file ./schema/centralized_crosschain.mol > ./contracts/centralized-crosschain/src/types.rs

.PHONY: schema